project_id = "forkast-prediction-market"

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.migrations]
enabled = true
schema_paths = [ "./migrations/*.sql" ]

[db.seed]
enabled = true
sql_paths = [ "./seeds/*.sql" ]
