name: Next.js CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium webkit

      - name: Create .env.test
        run: |
          cat <<'EOF' > .env.test
          ${{ secrets.ENV_TEST }}
          EOF

      - name: Run Playwright tests
        run: NODE_ENV=test npx playwright test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
        env:
          SUPABASE_URL: https://dummy
          SUPABASE_SERVICE_ROLE_KEY: dummy
          POSTGRES_URL: postgres://dummy:dummy@localhost:5432/dummy
          BETTER_AUTH_SECRET: 00000000000000000000000000000000
          NEXT_PUBLIC_REOWN_APPKIT_PROJECT_ID: dummy
          NEXT_PUBLIC_SITE_LOGO_SVG: <svg>dummy</svg>
