name: Next.js CI

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v5

      - name: Download node_modules
        uses: actions/download-artifact@v5
        with:
          name: node_modules
          path: node_modules

      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v5

      - name: Download node_modules
        uses: actions/download-artifact@v5
        with:
          name: node_modules
          path: node_modules

      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v5

      - name: Download node_modules
        uses: actions/download-artifact@v5
        with:
          name: node_modules
          path: node_modules

      - run: npm run build
        env:
          SUPABASE_URL: https://dummy
          SUPABASE_SERVICE_ROLE_KEY: dummy
          POSTGRES_URL: postgres://dummy:dummy@localhost:5432/dummy
          BETTER_AUTH_SECRET: 00000000000000000000000000000000
          NEXT_PUBLIC_REOWN_APPKIT_PROJECT_ID: dummy
          NEXT_PUBLIC_SITE_LOGO_SVG: <p>
