name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  sync:
    if: ${{ github.repository != 'forkast-prediction-market/forkast-prediction-market' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Configure upstream and fetch
        run: |
          git remote get-url upstream || git remote add upstream https://github.com/forkast-prediction-market/forkast-prediction-market.git
          git fetch upstream

      - name: Fix origin URL to fork
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git

      - name: Merge upstream/main into fork
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "Nothing to merge"

      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create dummy commit
        run: |
          git commit --allow-empty -m "chore: sync with forkast"

      - name: Push changes to origin
        run: |
          git push origin main
