name: Auto Commit (author = fork owner)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main, master]
    paths-ignore:
      - '.github/**'

permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git author/committer
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Run task that may change files
        run: |
          echo "$(date -u) :: heartbeat" >> .auto/heartbeat.log

      - name: Check for changes
        id: diff
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Force sync with upstream
        if: github.repository != 'forkast-prediction-market/forkast-prediction-market'
        run: |
          # Add upstream remote if not exists
          git remote get-url upstream || git remote add upstream https://github.com/forkast-prediction-market/forkast-prediction-market.git
          git fetch upstream

          # Force reset to upstream/main
          git reset --hard upstream/main
          git push --force origin main

      - name: Commit & push (main repo only)
        if: steps.diff.outputs.changed == 'true' && github.repository == 'forkast-prediction-market/forkast-prediction-market'
        run: |
          branch="$(git rev-parse --abbrev-ref HEAD)"
          git add -A
          git commit -m "chore: auto-commit [skip ci]"
          git push origin "$branch"
