name: Fork Sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  commit-after-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Configure upstream and fetch
        run: |
          git remote get-url upstream || git remote add upstream https://github.com/forkast-prediction-market/forkast-prediction-market.git
          git fetch upstream

      - name: Merge upstream/main into fork
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "Nothing to merge"

      - name: Create dummy commit
        run: |
          git commit --allow-empty -m "chore: sync with forkast"

      - name: Push changes to origin
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin main